// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaVenta.Server.Models;

public partial class EVENTO
{
    public int IdEvento { get; set; }

    public DateTime FechaEvento { get; set; }

    public string LugarEvento { get; set; }

    public string DescripcionEvento { get; set; }

    public decimal Precio { get; set; }

    public bool? Estado { get; set; }
}